require:
  - rubocop-rspec
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - 'vendor/*/**'
    - 'bin/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
